---
title: "Exploratory Data Analysis"
author: "Spiro Stilianoudakis"
date: "9/13/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Loading Libraries

```{r}
library(openxlsx)
library(dplyr)
library(ggplot2)
library(ggpubr)
library(reshape2)
library(sas7bdat)
library(lubridate)
library(tidyr)
library(tableone)
library(ggplot2)
```

# Set working directory

```{r}
setwd("C:/Users/stili/Documents/PAT_project/data")
```

# Reading in data

```{r}
pat_data <- read.csv("C:/Users/stili/Documents/PAT_project/data/pat_project_data.csv",
                    header=TRUE,
                    stringsAsFactors=FALSE)

dim(pat_data)
#291   7
str(pat_data)
```

# Exploratory Data Analysis

## Age

```{r}
summary(pat_data$Age)
#   Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
#  21.00   22.00   24.00   24.86   26.00   44.00 

ggplot(pat_data, aes(x=Age)) +   
   geom_histogram(aes(y=..density..), bins = 15) + 
   geom_density(aes(y=..density..), color="red", size=1) +
  ylab("Density") +
  theme_minimal() +
  theme_bw() +
  theme(axis.text.x = element_text(size = 15),
        axis.text.y = element_text(size = 15),
        axis.title.x = element_text(size = 20),
        axis.title.y = element_text(size = 20))
```

## Sex

```{r}
table(pat_data$Sex, exclude = "ifany")
#     F Female      M   Male 
#   111     36     85     59 

#recoding sex
pat_data$Sex[which(pat_data$Sex=="F")] <- "Female"
pat_data$Sex[which(pat_data$Sex=="M")] <- "Male"

table(pat_data$Sex, exclude = "ifany")
#Female   Male 
#   147    144 

pat_data %>% 
    group_by(Sex) %>% 
    summarize(count = n()) %>% 
    mutate(percent = count/sum(count)) %>% 
    ggplot(aes(x=Sex, y=count, fill=Sex)) +
    geom_col() +
    geom_text(aes(label = paste0(round(100 * percent, 1), "%")), vjust = -.5, size=5)+
    xlab("Sex") + 
    ylab("Count")+
    guides(fill=FALSE)+
    theme_bw()+
    theme(axis.text.x = element_text(size = 15),
        axis.text.y = element_text(size = 15),
        axis.title.x = element_text(size = 20),
        axis.title.y = element_text(size = 20))
```

## PAT

```{r}
summary(pat_data$PAT)
#   Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
#  15.00   19.00   20.00   20.35   22.00   30.00 

ggplot(pat_data, aes(x=PAT)) +   
   geom_histogram(aes(y=..density..), bins = 15) + 
   geom_density(aes(y=..density..), color="red", size=1) +
  ylab("Density") +
  theme_minimal() +
  theme_bw() +
  theme(axis.text.x = element_text(size = 15),
        axis.text.y = element_text(size = 15),
        axis.title.x = element_text(size = 20),
        axis.title.y = element_text(size = 20))
```

## Ethnicity

```{r}
table(pat_data$Ethnicity, exclude = "ifany")
#               A               AA  Afrian American African American            Asian 
#              32                5                1                4               57 
#           Black                C        Caucasian               CC  Didn't Identiry 
#               4               39               57                1                1 
#               H         Hispanic                M               ME    Middle Easten 
#               4                8                5               12                2 
#  Middle Eastern            White      White/Asian   White/Hispanic 
#               5               52                1                1 

#recoding ethnicity
pat_data$Ethnicity[which(pat_data$Ethnicity=="A" |
                           pat_data$Ethnicity=="Asian")] <- "Asian"

pat_data$Ethnicity[which(pat_data$Ethnicity=="AA" |
                           pat_data$Ethnicity=="Afrian American" |
                           pat_data$Ethnicity=="African American" |
                           pat_data$Ethnicity=="Black")] <- "African American"

pat_data$Ethnicity[which(pat_data$Ethnicity=="Middle Eastern" |
                           pat_data$Ethnicity=="Middle Easten" |
                           pat_data$Ethnicity=="ME")] <- "Middle Eastern"

pat_data$Ethnicity[which(pat_data$Ethnicity=="Hispanic" |
                           pat_data$Ethnicity=="H" |
                           pat_data$Ethnicity=="M")] <- "Hispanic"

 pat_data$Ethnicity[which(pat_data$Ethnicity=="White/Hispanic" |
                            pat_data$Ethnicity=="White/Asian" |
                            pat_data$Ethnicity=="Didn't Identiry")] <- "Unknown"

#pat_data$Ethnicity[which(pat_data$Ethnicity=="Hispanic" |
#                           pat_data$Ethnicity=="H" |
#                           pat_data$Ethnicity=="M" |
#                           pat_data$Ethnicity=="White/Hispanic" |
#                           pat_data$Ethnicity=="Middle Eastern" |
#                           pat_data$Ethnicity=="Middle Easten" |
#                           pat_data$Ethnicity=="ME" |
#                           pat_data$Ethnicity=="Didn't Identiry")] <- "Other"

pat_data$Ethnicity[which(pat_data$Ethnicity=="Caucasian" |
                           pat_data$Ethnicity=="C" |
                           pat_data$Ethnicity=="CC" |
                           pat_data$Ethnicity=="White")] <- "White"

table(pat_data$Ethnicity, exclude = "ifany")

pat_data$Ethnicity <- factor(pat_data$Ethnicity, levels=c("White", "African American", "Asian", "Hispanic", "Middle Eastern", "Unknown"))

pat_data %>% 
    group_by(Ethnicity) %>% 
    summarize(count = n()) %>% 
    mutate(percent = count/sum(count)) %>% 
    ggplot(aes(x=Ethnicity, y=count, fill=Ethnicity)) +
    geom_col() +
    geom_text(aes(label = paste0(round(100 * percent, 1), "%")), vjust = -.5, size=5)+
    xlab("Ethnicity") + 
    ylab("Count")+
    guides(fill=FALSE)+
    theme_bw()+
    theme(axis.text.x = element_text(size=15,
                                     angle = 45,
                                     hjust = 1),
        axis.text.y = element_text(size = 15),
        axis.title.x = element_text(size = 20),
        axis.title.y = element_text(size = 20))
```

## TES

```{r}
summary(pat_data$TES)
#   Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
#   0.00    8.00   20.00   27.32   32.00  224.00 

ggplot(pat_data, aes(x=TES)) +   
   geom_histogram(aes(y=..density..), bins = 15) + 
   geom_density(aes(y=..density..), color="red", size=1) +
  ylab("Density") +
  theme_minimal() +
  theme_bw() +
  theme(axis.text.x = element_text(size = 15),
        axis.text.y = element_text(size = 15),
        axis.title.x = element_text(size = 20),
        axis.title.y = element_text(size = 20))
```

## Time

```{r}
summary(pat_data$Time)
#   Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
#  3.670   7.255   8.400   8.984  10.000  25.200 

ggplot(pat_data, aes(x=Time)) +   
   geom_histogram(aes(y=..density..), bins = 15) + 
   geom_density(aes(y=..density..), color="red", size=1) +
  xlab("Time of completion of FM-100 test (minutes)")+
  ylab("Density") +
  theme_minimal() +
  theme_bw() +
  theme(axis.text.x = element_text(size = 15),
        axis.text.y = element_text(size = 15),
        axis.title.x = element_text(size = 20),
        axis.title.y = element_text(size = 20))
```

## Color Acuity

```{r}
table(pat_data$Color.Acuity, exclude = "ifany")
#  A   P   S 
#151   8 132 

pat_data$Color.Acuity <- ifelse(pat_data$Color.Acuity=="A", "Average",
                                ifelse(pat_data$Color.Acuity=="S", "Superior", "Poor"))
table(pat_data$Color.Acuity, exclude = "ifany")
# Average     Poor Superior 
#     151        8      132

pat_data$Color.Acuity <- factor(pat_data$Color.Acuity, levels=c("Poor", "Average", "Superior"))

pat_data %>% 
    group_by(Color.Acuity) %>% 
    summarize(count = n()) %>% 
    mutate(percent = count/sum(count)) %>% 
    ggplot(aes(x=Color.Acuity, y=count, fill=Color.Acuity)) +
    geom_col() +
    geom_text(aes(label = paste0(round(100 * percent, 1), "%")), vjust = -.5, size=5)+
    xlab("Color Acuity Score") + 
    ylab("Count")+
    guides(fill=FALSE)+
    theme_bw()+
    theme(axis.text.x = element_text(size = 15),
        axis.text.y = element_text(size = 15),
        axis.title.x = element_text(size = 20),
        axis.title.y = element_text(size = 20))
```

# Saving recoded/cleaned data

```{r}
saveRDS(pat_data, "C:/Users/stili/Documents/PAT_project/data/pat_data.rds")
```

