---
title: "Modelling"
author: "Spiro Stilianoudakis"
date: "11/10/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Loading Libraries

```{r}
library(openxlsx)
library(dplyr)
library(ggplot2)
library(ggpubr)
library(reshape2)
library(sas7bdat)
library(lubridate)
library(tidyr)
library(tableone)
library(ggplot2)
library(grid)
library(gridExtra)
library(car)
library(MASS)
library(tableone)
```

# Set working directory

```{r}
setwd("C:/Users/stili/Documents/PAT_project/data")
```

# Reading in data

```{r}
pat_data <- readRDS("C:/Users/stili/Documents/PAT_project/data/pat_data.rds")
```

# Cleaning 

```{r}
pat_data$Ethnicity <- as.character(pat_data$Ethnicity)
pat_data$Ethnicity[which(pat_data$Ethnicity=="African American" |
                           pat_data$Ethnicity=="Hispanic" |
                           pat_data$Ethnicity=="Middle Eastern" |
                           pat_data$Ethnicity=="Unknown")] <- "Other"
pat_data$Ethnicity <- factor(pat_data$Ethnicity, levels=c("White",
                                                          "Asian",
                                                          "Other"))
table(pat_data$Ethnicity)

pat_data$Sex <- factor(pat_data$Sex)

pat_data$Color.Acuity2 <- factor(ifelse(pat_data$Color.Acuity=="Superior", "0-16", ">16"), levels=c(">16", "0-16"))
table(pat_data$Color.Acuity2)

pat_data$logTES <- log(pat_data$TES+1)
```

# Table 1

```{r}
CreateTableOne(c("Age", "Sex", "Ethnicity", 'TES', "Color.Acuity2", "Time", "PAT"), 
               data=pat_data)
```

# Modelling PAT 

```{r}
model1 <- lm(logTES ~ PAT + Age + Sex + Ethnicity + Time,
             data=pat_data)
summary(model1)
round(confint(model1),2)
paste0(round(coef(model1),2), " ", "(", round(confint(model1),2)[,1], ",", round(confint(model1),2)[,2], ")")

round((exp(coef(model1)) - 1) * 100,2)


a1<-aov(PAT ~ Color.Acuity2, data=pat_data)
TukeyHSD(a1)

pat_data$Color.Acuity2 <-relevel(pat_data$Color.Acuity2,ref="0-16")
pat_data$Color.Acuity2 <- factor(ifelse(pat_data$Color.Acuity2=="0-16", "Yes", "No"), levels = c("Yes", "No"))

ggplot(pat_data, aes(x=Color.Acuity2, y = PAT, fill=Color.Acuity2))  + 
    stat_boxplot(geom ='errorbar', width = 0.2) + 
    geom_boxplot() +
    xlab("Superior Color Acuity") +
    guides(fill=FALSE) +
    geom_signif(test = "t.test", 
                comparisons = list(c("Yes", "No")),
                vjust = 0,
                textsize = 4,
                size = .5,
                step_increase = .08,
                color="black") +
    theme_minimal()+
    theme_bw() +
    theme(axis.text.x = element_text(size = 15),
        axis.text.y = element_text(size = 15),
        axis.title.x = element_text(size = 20),
        axis.title.y = element_text(size = 20))

```

